package java8_programs;

import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class MapFunction {
    public static void main(String[] args) {

        int sum = IntStream.rangeClosed(0, 100).sum();
        System.out.println("sum :: " +sum);

        List<Integer> list1 = Arrays.asList(1,9,16,9,4,5,6,10,2,4);
        List<Integer> collect2 = list1.stream().distinct().collect(Collectors.toList());
        System.out.println("collect2 ::::" +collect2);

        Set<Integer> set = new HashSet<>();
        List<Integer> collect1 = list1.stream().filter(i -> !set.add(i)).collect(Collectors.toList());
        System.out.println("collect ::: " + collect1);

        // making the array list object
        ArrayList<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");
        System.out.println("List of fruit-" + fruit);


        List<String> collect3 = fruit.stream().sorted().collect(Collectors.toList());
        System.out.println("collect3 :: " +collect3);

        // lets use map() to convert list of fruit
        List list = fruit.stream()
                .map(s -> s.length())
                .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);

        List<String> collect = fruit.stream().map(i -> (i.length() % 2 == 0) ? i + "000" : i + "001").collect(Collectors.toList());
        System.out.println("collect :::" +collect);

        String version = "v1234";
        System.out.println("v" + (Integer.parseInt(version.replaceAll("[^0-9]", ""))+1));



    }


}
